---
title: "CarVsDriverEDA"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)

df_avgLapTimes <- read.csv("processed_data/std_avg_laptime.csv")
df_cleandata <- read_csv("processed_data/clean_f1.csv")
```

```{r fig.width = 20,fig.height=10}
df_avgLapTimes %>%
  mutate(driver_name = fct_reorder(as.character(driver_name),std_avg_lap))%>%
  ggplot(mapping = aes(x = driver_name, y = std_avg_lap)) +
  geom_boxplot() +
  ylim(-2,2) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90,vjust = 0.5, hjust = 1)) 
```

```{r}
df_avgLapTimes %>%
  mutate(constructor_name = fct_reorder(as.character(constructor_name),std_avg_lap, .fun = mean))%>%
  ggplot(mapping = aes(x = constructor_name, y = std_avg_lap)) +
  geom_boxplot()+
  ylim(-2,2)+
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90,vjust = 0.5, hjust = 1))+
  labs(x = "Vehicle Constructor Name",y = "Standardized Average Lap Time (ms)")
```

```{r fig.width = 20,fig.height=10}
df_cleandata %>%
  mutate(driver_name = fct_reorder(as.character(driver_name),positionOrder))%>%
  ggplot(mapping = aes(x = driver_name, y = positionOrder)) +
  geom_boxplot() +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90,vjust = 0.5, hjust = 1))+
  labs(x = "Driver Name",y = "Final position ranking")

df_cleandata %>%
  mutate(constructor_name = fct_reorder(as.character(constructor_name),positionOrder, .fun = mean))%>%
  ggplot(mapping = aes(x = constructor_name, y = positionOrder)) +
  geom_boxplot()+
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90,vjust = 0.5, hjust = 1))+
  labs(x = "Vehicle Constructor Name",y = "Final position ranking")
```

```{r fig.width = 20,fig.height=10}
df_cleandata %>%
  group_by(driver_name) %>%
  summarise(mean_position = mean(positionOrder)) %>%
  mutate(driver_name = fct_reorder(as.character(driver_name),mean_position))%>%
  ggplot(mapping = aes(x = driver_name, y = mean_position)) +
  geom_point() +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90,vjust = 0.5, hjust = 1))+
  labs(x = "Driver Name",y = "Final position ranking")

df_cleandata %>%
  group_by(constructor_name) %>%
  summarise(mean_position = mean(positionOrder)) %>%
  mutate(constructor_name = fct_reorder(as.character(constructor_name),mean_position))%>%
  ggplot(mapping = aes(x = constructor_name, y = mean_position)) +
  geom_point()+
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90,vjust = 0.5, hjust = 1))+
  labs(x = "Vehicle Constructor Name",y = "Final position ranking")
```